name: flutter_ocr_android
description: Android implementation of the flutter_ocr plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

flutter:
  plugin:
    implements: flutter_ocr
    platforms:
      android:
        package: com.example.verygoodcore
        pluginClass: FlutterOcrPlugin
        dartPluginClass: FlutterOcrAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_ocr_platform_interface:
    path: ../flutter_ocr_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
